// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv-TROYOk7bSnFbZsaJcwhO_f4M5wyPf0',
    appId: '1:856180546422:web:b42206943b1b75d7d0f857',
    messagingSenderId: '856180546422',
    projectId: 'projectetsppb',
    authDomain: 'projectetsppb.firebaseapp.com',
    storageBucket: 'projectetsppb.firebasestorage.app',
    measurementId: 'G-8D71QKLKEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWbVZPkt9LQNv80Nmzbn3_N3rxRpqMqPY',
    appId: '1:856180546422:android:40358791013c373ed0f857',
    messagingSenderId: '856180546422',
    projectId: 'projectetsppb',
    storageBucket: 'projectetsppb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD4AkJ24geSelU7iwY4k3CDeJK16Yr9W0',
    appId: '1:856180546422:ios:a0ec9456b7117003d0f857',
    messagingSenderId: '856180546422',
    projectId: 'projectetsppb',
    storageBucket: 'projectetsppb.firebasestorage.app',
    iosBundleId: 'com.naufal.tugasets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD4AkJ24geSelU7iwY4k3CDeJK16Yr9W0',
    appId: '1:856180546422:ios:a0ec9456b7117003d0f857',
    messagingSenderId: '856180546422',
    projectId: 'projectetsppb',
    storageBucket: 'projectetsppb.firebasestorage.app',
    iosBundleId: 'com.naufal.tugasets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv-TROYOk7bSnFbZsaJcwhO_f4M5wyPf0',
    appId: '1:856180546422:web:b2f7620630167185d0f857',
    messagingSenderId: '856180546422',
    projectId: 'projectetsppb',
    authDomain: 'projectetsppb.firebaseapp.com',
    storageBucket: 'projectetsppb.firebasestorage.app',
    measurementId: 'G-MYZP5Q08J6',
  );
}
